PIN_ROOT ?= /home/iliana/Downloads/pin-3.30-98830-g1d7b601b3-gcc-linux
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
include $(CONFIG_ROOT)/makefile.config
include makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules
